version = 2

songs = "*.md"

notation = "german"

[[output]]
file = "songbook.pdf"
sans_font = true

[[output]]
file = "songbook.json"
script = "chords"

[book]
title = "Spěvník"
subtitle = "Lukas"
chorus_label = "R"
